### ISSUE TITLE
pattern with or without rt/hc?

### ISSUE THREAD

**Issue by aaronspring** [ecmwf-lab/climetlab-s2s-ai-competition#12]
currently the readme is:

- https://storage.ecmwf.europeanweather.cloud/s2s-ai-competition/data/{datasetname}/0.1.43/grib/{param}-rt-{date}.grib
- wget https://storage.ecmwf.europeanweather.cloud/s2s-ai-competition/data/training-set-forecast-cwao/0.1.43/grib/tp-20200102.grib

the data path is without `-rt` but the readme pattern still includes it. Is the goal to have it in the file name or have the name without `rt` or `hc`? @floriankrb

**Comment by floriankrb** [comment]
Thanks for checking, this was a typo. The fctype (hindcast or forecast) is indeed written before in the url.
