### ISSUE TITLE
suggestion for filenames

### ISSUE THREAD

**Issue by aaronspring** [ecmwf-lab/climetlab-s2s-ai-competition#13]
currently file names have the following pattern on https://storage.ecmwf.europeanweather.cloud/s2s-ai-competition/data/training-set-forecast-kwbc/0.1.43/netcdf/index.html:

https://storage.ecmwf.europeanweather.cloud/s2s-ai-competition/data/training-set-forecast-kwbc/0.1.43/netcdf/2t-20200102.nc

Observation: If a user would use `wget` to download files, the information about the model and whether forecast or reforecast gets lost. wget is not encouraged but still the most robust way to access.
Solution: name the files {param}-{model}-{type}-{date}.{format} Or do you think that gets too long?

lets maybe briefly talk about this tomorrow.

**Comment by floriankrb** [comment]
Good point. Having subdirectories (using /) is very convenient and I didn't like much having duplicated information in the url with {model}/{type}/{param}-{model}-{type}-{date}.{format}. The choice is yours :-)

**Comment by aaronspring** [comment]
if you anyways have to upload the data new for the new version, i'd prefer ` {model}/{type}/{param}-{model}-{type}-{date}.{format}` if feasible.

**Comment by floriankrb** [comment]
what about `https://storage.ecmwf.europeanweather.cloud/s2s-ai-competition/data/{dataset}/{version}/{model}/{fctype}/{format}/{param}-{model}-{fctype}-{date}.{format}` 

with : 
- format is  'grib', 'zarr', 'nc'  ('netcdf' ?)
- fctype is 'forecast' 'hindcast'
- model :  cwao, ecmf and kwbc or eccc, ncep, ecmwf ?
- dataset : 'training-input' 'forecast-input' 'forecast-benchmark' (and we will have also 'observations') 
- date : I plan to follow the iso date format : YYYY-MM-DD (and not YYYYMMDD)

**Comment by aaronspring** [comment]
>     * format is  'grib', 'zarr', 'nc'  ('netcdf' ?)

I wouldnt list zarr, as zarr has a different path. I guess zarr is combining all files into a huge zarr. the ending `nc` could also be used in climetlab and for the url. the mapping `netcdf` to `nc` is obvious.
 
>     * fctype is 'forecast' 'hindcast'
On IRI its called reforecasts and forecasts. I also understood Andy that he prefers reforecasts/forecasts. climetlab may understand both ways?

>     * model :  cwao, ecmf and kwbc or eccc, ncep, ecmwf ?
This is about the difference between origin center and model name from that center, right? no preference for the naming, climetlab could do the mapping internally though.


>     * dataset : 'training-input' 'forecast-input' 'forecast-benchmark' (and we will have also 'observations')
agreed.

>     * date : I plan to follow the iso date format : YYYY-MM-DD (and not YYYYMMDD)
for the filenames it doesnt matter too much. But I would prefer to use a different separator: above you use `-` to separate `{fctype}-{date}`. do to `url.split('-')` nicely I would prefer either a different first separator or no date separator.
