### ISSUE TITLE
demo using s2s data with zarr format

### ISSUE THREAD

**Issue by aaronspring** [ecmwf-lab/climetlab-s2s-ai-competition#5]
I tried to open S2S output on renkulab. There I have a 8GB memory limit on renkulab, which lets the kernel crash often. I couldnt figure out the s3 bucket to access `zarr` direct with `s3fs`. is it possible to pass options like `chunks` to `open_mfdataset`?

`netcdf` produces 10k tasks. probably a better chunking strategy is possible.

trying something like:
```python
import climetlab as cml
import xarray as xr
dates=xr.cftime_range(start='2020-01-02', end='2020-12-31', freq='7D')  # kernel dies even for just two dates
dates=dates.to_datetimeindex()
dates=[d for d in dates.strftime("%Y-%m-%d")]
ds = cml.load_dataset("s2s-ai-competition-reference-set", date=dates, parameter=['tp'],format='zarr')
ds.to_xarray().isel(step=slice(3*7,4*7)).mean('step').to_zarr('../ECMWF_2020_week3.zarr')
```

**Comment by floriankrb** [comment]
Part of the data have been uploaded as another zarr, perhaps you want to give another try, following this example : https://nbviewer.jupyter.org/github/ecmwf-lab/climetlab-s2s-ai-competition/blob/master/notebooks/demo_zarr.ipynb

**Comment by aaronspring** [comment]
maybe we can first run the notebooks through CI.

**Comment by aaronspring** [comment]
in climpred we use `asv` to benchmark RAM usage: https://github.com/pangeo-data/climpred/blob/477af0906898695a87203fcd1c46e8c48f0bee9e/asv_bench/benchmarks/benchmarks_hindcast.py#L123

**Comment by aaronspring** [comment]
> PS : Your slicing seems to take 7 dates, from date 21 to 28.
> 
> > > > xr.cftime_range(start='2020-01-02', end='2020-12-31', freq='7D')[21:28]
> > > > CFTimeIndex([2020-05-28 00:00:00, 2020-06-04 00:00:00, 2020-06-11 00:00:00,
> > > > 2020-06-18 00:00:00, 2020-06-25 00:00:00, 2020-07-02 00:00:00,
> > > > 2020-07-09 00:00:00],
> > > > dtype='object', length=7, calendar='gregorian', freq='7D')

I do not understand you comment about the 7 dates. I want to use weekly step/lead, therefore 7. or do I have some wrong assumptions here? @floriankrb in the end we want to use bi-weekly for the competition.

**Comment by floriankrb** [comment]
I was commenting on the "isel(step=slice(3*7,4*7)" part, to point that you may have meant "isel(step=slice(3,4)".

**Comment by aaronspring** [comment]
I want to get week 3, there choosing day step 21-28

**Comment by floriankrb** [comment]
Then, this would be ".sel", not ".isel"

**Comment by aaronspring** [comment]
ah. now I see. I choose `isel` because the underlying array holds nanoseconds values. As index 0 is step 0 days, isel and sel end up being the same, dont they?

**Comment by floriankrb** [comment]
.isel selects data by position, but .sel select data by label. 
I believe that "isel(step=slice(3*7,4*7)" will select 7 values, while  "sel(step=slice(3*7,4*7)" will not.

**Comment by aaronspring** [comment]
I want to select 7 values for weekly averaging
