### ISSUE TITLE
refactor github workflows

### ISSUE THREAD

**Issue by floriankrb** [ecmwf-lab/climetlab-s2s-ai-competition#8]
To ensure consistency with climetlab (and ideally across all plugins), it would be nice to have a similar github workflow such as this one https://github.com/ecmwf/climetlab/blob/master/.github/workflows/check-and-publish.yml, where the target "deploy" depends on the target "checks".

 @aaronspring do you want to take this ? Or would you rather that I start it to clarify the idea ?

**Comment by aaronspring** [comment]
I'd prefer you start. I didn't get the full idea yet.

**Comment by floriankrb** [comment]
I believe this is mostly here. The dependencies are not so easy to handle. Eventually I relied on installing climetlab first (pip install climetlab), then installing the package (which has climetlab as a dependency).
I had to disable the long tests (I believe that downloading data takes long, or merging data), I kept only the zarr test which is fast.

**Comment by aaronspring** [comment]
Eventually these long tests reflect the user experience.

**Comment by aaronspring** [comment]
A current problem is that pip install clinetlab-s2s doesn't work because it requires climetlab 0.4.5 but the latest release is 0.4.4. The pre releases don't count.

**Comment by aaronspring** [comment]
Ok. Seems to work now.

**Comment by aaronspring** [comment]
currently CI workflow doesnt fail when flake errors are found

**Comment by aaronspring** [comment]
#11 tests notebooks but fails currently and adds badges for binder, ci and pypi
